coreos-postinst
The "real" cgpt is actually under old_bins, so search there first. Also
it isn't safe to just point the existing loader at a new lib directory,
the loader should match the libc version. Using the loader directly
should fix an issue we had during the last attempted glibc upgrade.
=> postinst: search for cgpt, use the new system's ld.so

SConstruct, main.cc, testrunner.cc, update_engine_client.cc
Note: glib >= 2.36 is now required. CoreOS currently ships 2.40.0
=> Fix a warning, make noise about two others.

SConstruct, delta_diff_generator.cc, delta_performer.cc, payload_state.cc
Related ChromiumOS commit that also fixed these errors:
https://chromium.googlesource.com/chromiumos/platform/update_engine/+/75039d7397f03dff77bdf4e26398049ff88edc4c
Differences from that commit:
- off_t is signed, so don't cast to unsigned
- size_t can use %zu, no casting required
=> build: fix format string warnings

delta_diff_generator_unittest.cc, delta_performer.cc
Remove the unused routines DumpUpdateProto(), ExtentsToString() and
VectOfExts().  Fixes build errors like these when building with newer compilers
(gcc-4.9.2) that have better unused function checking:
delta_performer.cc: error: 'void chromeos_update_engine::{anonymous}::DumpUpdateProto(const chromeos_update_engine::DeltaArchiveManifest&)' defined but not used
Signed-off-by: Geoff Levand <geoff@infradead.org>
=> Remove unused routines

coreos-postinst
Systems that have grub configured to boot the kernel from the ESP will need
to have the kernel copied out of the image into the ESP for now until we
add support for providing additional update engine payloads.
=> Copy the kernel to the ESP if necessary

Makefile.am, configure.ac
Missed this in 918a9d80, I thought I was building everything but
overlooked that configure wasn't enabling this option.
=> build: fix delta_generator and enable by default

coreos-postinst, src/update_engine/delta_performer.cc, src/update_engine/delta_performer.h, src/update_engine/download_action.cc, src/update_engine/filesystem_copier_action.cc, src/update_engine/omaha_response_handler_action.cc, src/update_engine/postinstall_runner_action.cc, src/update_engine/postinstall_runner_action.h, src/update_engine/update_attempter.cc, src/update_engine/utils.cc, src/update_engine/utils.h
Distributing the kernel outside the filesystem is necessary for the combination of Secure Boot and verified filesystems, so we need Update Engine to be able to handle update images that contain a separate kernel payload and copy it to the right place.
=> Support kernel payloads in Update Engine

src/update_engine/update_attempter.cc, src/update_engine/utils.cc, src/update_engine/utils.h, src/update_engine/utils_unittest.cc
update_engine is the only remaining user of the tool 'crossystem' which
does not provide any useful functionality on CoreOS. This particular
check was for whether the physical "dev mode" switch on a ChromeBook had
been enabled.
=> utils: remove support for ChromeOS "dev mode"

src/update_engine/delta_performer.cc, src/update_engine/delta_performer.h, src/update_engine/delta_performer_unittest.cc, src/update_engine/download_action.cc, src/update_engine/filesystem_copier_action.cc, src/update_engine/generate_delta_main.cc
Right now if we get an update that contains no kernel, we'll still set up
the FileCopierAction for the kernel and try to run it. This will break if
the installed image doesn't contain kernels in the new location. Just exit
early to avoid that from happening.
=> Fix updates with no kernel image

configure.ac
Cleans up build directory and newer versions of automake complain if the option is missing.
=> build: enable subdir-objects automake option

.gitignore, coreos-postinst, src/update_engine/delta_diff_generator.cc, src/update_engine/delta_diff_generator.h, src/update_engine/delta_performer.cc, src/update_engine/delta_performer.h, src/update_engine/delta_performer_unittest.cc, src/update_engine/download_action.cc, src/update_engine/download_action_unittest.cc, src/update_engine/filesystem_copier_action.cc, src/update_engine/filesystem_copier_action.h, src/update_engine/filesystem_copier_action_unittest.cc, src/update_engine/full_update_generator.cc, src/update_engine/full_update_generator.h, src/update_engine/full_update_generator_unittest.cc, src/update_engine/generate_delta_main.cc, src/update_engine/install_plan.cc, src/update_engine/install_plan.h, src/update_engine/omaha_response_handler_action.cc, src/update_engine/update_attempter.cc, src/update_engine/update_attempter_unittest.cc, src/update_engine/update_metadata.proto
Resurrection the old kernel partition code to update kernel files has proven tricky. Instead just pull out the old code and write something new that works better for files. The new kernel update code will come in a following PR.
=> Remove old kernel update code

configure.ac, src/update_engine/generate_delta_main.cc, src/update_engine/main.cc, src/update_engine/update_engine_client.cc
gflags 2.0 and earlier used the `google` namespace while versions 2.1
and 2.1.1 switch to the `gflags` namespace, breaking both API and ABI
compatibility. Then 2.1.2 restores 2.0 ABI compatibility and provides a
`GFLAGS_NAMESPACE` macro.  Considering a year passed between 2.1.1 and
2.1.2 and the latter still isn't marked stable on Gentoo we define the
macro if it isn't provided.
Use of pkg-config has been removed because 2.1 and later dropped
libgflags.pc in the process of moving to cmake. :(
(note: we will be sticking with gflags 2.0 for now but this has been kicking around in my local tree so long I may as well just commit it)
=> build: detect which namespace gflags uses

src/update_engine/delta_diff_generator_unittest.cc, src/update_engine/extent_ranges.cc, src/update_engine/extent_ranges.h, src/update_engine/extent_ranges_unittest.cc, src/update_engine/graph_utils.cc, src/update_engine/graph_utils_unittest.cc
The test `PayloadProcessorTest.RunAsRootSmallImageSignGeneratedTest` intermittently fails, this appears to be the fix, from 2013... It does not impact current systems since it only causes issues with delta updates.
AU: Don't use sparse holes as scratch space in the delta generator.
This patch fixes a number of bugs related to handling of sparse holes
in the context of scratch space in the delta diff generator and adds
appropriate unit tests. Most notably:
- Ignore sparse holes for the purposes of ExtentRanges. This prevents
the generator from using sparse holes as scratch.
- Adds two unit tests to catch using sparse holes as scratch in a more
deterministric way.
- Handle correctly sparse holes in
GraphUtils::AppendBlockToExtents. For example, previously, if one
adds block 0 to a …
=> Port fix for intermittant test failures from ChromiumOS

src/update_engine/action_processor.h, src/update_engine/delta_metadata.cc, src/update_engine/delta_metadata.h, src/update_engine/install_plan.cc, src/update_engine/install_plan.h, src/update_engine/payload_processor.cc, src/update_engine/payload_processor.h, src/update_engine/payload_signer.cc, src/update_engine/payload_state.cc, src/update_engine/update_metadata.proto, src/update_engine/utils.cc
A bit of refactoring and updates the metadata protobuf format for kernels.
I want InstallBlob to be extensible so adding new values to the enum needs to be safe but I am not sure what will happen if old code gets a new enum value. Whether it is graceful or aborts might even depend on whether the code is built with -DNDEBUG or not. Need to test to confirm... :-/
=> Prep work for kernel updates

coreos-postinst
When running an update on slow media, i.e. USB sticks
the FilesystemCopierAction seems to clear the partition label for a brief
moment. `lsblk` then retrieves an empty label in postinst stage, causing
a failure. Interestingly, running `gdisk` on the affected media and just
printing the partition table "refreshes" the label for subsequent `lsblk`
runs.
Replacing `lsblk` with `blkid` returns the correct label every time.
=> use 'blkid' instead of 'lsblk' to get partition label

coreos-postinst
since systemd v226, virtio_net nics will use predictable device naming.
this could break existing network configurations, so for upgrades from
old versions of coreos, we install a networkd .link file to keep old nic
names the same.
=> coreos-postinst: install link file for virtio_net naming compatibility

coreos-postinst, src/update_engine/postinstall_runner_action.cc, src/update_engine/postinstall_runner_action.h, src/update_engine/postinstall_runner_action_unittest.cc, src/update_engine/update_attempter.cc, src/update_engine/update_attempter_unittest.cc
This is left over from our previous scheme of using a new app-id to
determine how the kernel would get updated. No longer applicable.
update_engine's behavior now should match that of the
older version of update_engine we are still shipping in CoreOS.
This reverts commits 7730651c57ec09f1d20ed10ad5835b6ebe70f79a, be204cd, 7f342ac,
and partially reverts f4157edb80cd4169caef317da6438d4dfa901018,
=> coreos-postinst: revert app-id checking

src/update_engine/delta_diff_generator.cc, src/update_engine/delta_diff_generator.h, src/update_engine/generate_delta_main.cc, src/update_engine/payload_processor.cc, src/update_engine/update_metadata.proto
@mjg59 pointed out Blob was a confusing choice because that term is used
in many other contexts in this code base. Instead match the existing
`InstallOperation` name and use `InstallInfo` and `InstallProcedure`.
=> update_metadata: drop the term Blob in structure names

src/update_engine/generate_delta_main.cc
Long standing bug: Write returns bool, not an errno.
=> generate_delta_main: fix usage of the payload processor

configure.ac, src/update_engine/generate_delta_main.cc, src/update_engine/main.cc, src/update_engine/test_http_server.cc, src/update_engine/testrunner.cc
By default glog outputs a number of log files to /tmp and very little to
stderr which is never what we want in CoreOS. Add an explicit check that
glog was built with gflags support so logging options are available.
=> update_engine: change default log target to stderr

coreos-postinst
Side note: given that postinst is shipped in the image along side cgpt
and ld.so we could define both of these paths at compile time instead of
searching at run time. Plumbing that through the ebuild, configure, and
this script is more than I want to deal with at just this moment though.
=> coreos-postinst: search for ld.so instead of assuming amd64

Makefile.am
protobuf 1.6 and later includes descriptor.proto and descriptor.pb.h
which emerge may install in any order it likes. If they happen to be
installed in reverse order the old make rule will attempt to rebuild
/usr/include/google/protobuf/descriptor.pb.h which won't work.
=> build: only regenerate our own protobuf sources

src/update_engine/ext2_metadata_unittest.cc, src/update_engine/postinstall_runner_action_unittest.cc, src/update_engine/test_utils.cc, src/update_engine/utils.cc
Images should never be generated from a journaled filesystem. Attempting
to shove the 4MB journal in the test filesystem normally isn't a big
deal but sometimes it appears to tickle something problematic in the
bsdiff algorithm, taking as long as 15-20 minutes to run.
So lets just not do that shall we? :-P
=> test_utils: use ext2 instead of ext3

src/update_engine/download_action.cc, src/update_engine/update_attempter.cc
During previous refactoring I removed some rather complicated throttling
logic around this log line. Also, the function calls another in
update_attempter (aka delegate) which already includes some a throttle
for dbus events so lets just log from there instead.
=> download_action: remove unthrottled download progress logging

src/update_engine/payload_processor_unittest.cc
Passing a mix of bools and enums is confusing and hard to extend.
=> payload_processor_unittest: move test parameters into state struct

src/update_engine/delta_diff_generator.cc, src/update_engine/delta_diff_generator.h, src/update_engine/full_update_generator.cc, src/update_engine/full_update_generator.h, src/update_engine/full_update_generator_unittest.cc, src/update_engine/generate_delta_main.cc, src/update_engine/payload_processor_unittest.cc
Adds support for creating payloads that include kernels outside of the main filesystem. update_engine cannot yet install those kernels but but at the very least the payload_processor unit test has been updated to ensure the unsupported kernel is gracefully skipped.
Depends on https://github.com/coreos/update_engine/pull/113 and https://github.com/coreos/update_engine/pull/115
=> Add kernel support to delta_generator

src/update_engine/delta_performer.cc, src/update_engine/delta_performer.h, src/update_engine/install_plan.cc, src/update_engine/install_plan.h, src/update_engine/payload_processor.cc, src/update_engine/payload_processor.h, src/update_engine/payload_processor_unittest.cc
This is just enough to get update_engine to write out kernels included in the payload. A few more pieces are still needed:
- copy the current running kernel prior to update (required for applying deltas)
- verify the kernel after update has been applied
- inform the postinst script that it does not need to copy the kernel itself
=> Add support for updating kernels

src/update_engine/kernel_verifier_action.cc, src/update_engine/payload_processor.cc, src/update_engine/payload_processor.h, src/update_engine/update_attempter.cc, src/update_engine/update_attempter_unittest.cc
This completes the kernel update code. Last piece will be to update the post-install script action so the script won't clobber the kernel update_engine already installed.
=> Enable kernel verification

src/update_engine/kernel_copier_action.cc, src/update_engine/omaha_response_handler_action.cc
The bootloader configuration in CoreOS <= 522.x.x was SYSLINUX based and used different install paths. If update_engine is running on such a system it shouldn't install kernels to the modern location since that would be wasting space in a somewhat small partition.
The post install script can remain as-is to support these systems, update_engine can just ignore the kernel.
=> Skip kernel update on really old systems

src/update_engine/delta_diff_generator.cc
Fixes passing payloads with extra procedures (e.g. a kernel) to old
versions of update_engine without support for the new manifest format.
Also skip operations without any data. Doesn't currently impact anything
as this only applies to MOVE operations which won't appear in kernels.
=> delta_diff_generator: copy data_sha256_hash to dummy operations

coreos-postinst, src/update_engine/kernel_copier_action.cc
Kernels being a plain old file could potentially get deleted somehow and
that seems like a reasonable situation to recover from, particularly
since full updates don't even need the old kernel anyway.
This does mean that a kernel will get created on a few systems that
don't actually need it. Systems created after 522.x.x but before 668.x.x
read the kernel directly from /usr. Not a great way to know the
difference so lets favor simplicity and ignore that case.
The postinst script has been updated to match.
=> kernel_copier_action: tolerate missing source kernels

configure.ac, src/update_engine/omaha_response_handler_action.cc, src/update_engine/utils.cc
In order to support verity we need the smarts of rootdev to resolve the
underlying partition instead of the dm block device. As the name implies
the library's default entry point `rootdev` resolves "/" but it also
exposes the oddly named `rootdev_wrapper` that can handle other devices.
Previously rootdev was removed in commit 78e5c78ce4a805566d5a63614d0db5ab7656368d.
=> utils: resume using the rootdev library to detect the boot device

src/update_engine/update_check_scheduler.cc, src/update_engine/update_check_scheduler.h, src/update_engine/update_check_scheduler_unittest.cc, src/update_engine/utils.cc, src/update_engine/utils.h, src/update_engine/utils_unittest.cc
This is not applicable to CoreOS like it would have been ChromeOS and
breaks perfectly legitimate installs.
Fixes https://github.com/coreos/bugs/issues/1587
=> update_check_scheduler: remove check for removable boot devices

src/update_engine/omaha_request_params.cc
The new ignition based GCE OEM installs oem-release to /usr/share/oem
but not /etc as it did in the past. Fix reporting OEM on these systems.
=> omaha_request_params: accept alternate location of oem-release

Makefile.am, src/update_engine/action_processor.h, src/update_engine/delta_diff_generator.cc, src/update_engine/delta_diff_generator.h, src/update_engine/delta_performer.cc, src/update_engine/generate_delta_main.cc, src/update_engine/http_common.cc, src/update_engine/http_common.h, src/update_engine/install_plan.cc, src/update_engine/install_plan.h, src/update_engine/omaha_request_params.cc, src/update_engine/omaha_request_params.h, src/update_engine/omaha_response_handler_action.cc, src/update_engine/omaha_response_handler_action.h, src/update_engine/payload_processor.cc, src/update_engine/payload_processor.h, src/update_engine/payload_processor_unittest.cc, src/update_engine/payload_state.cc, src/update_engine/pcr_policy_post_action.cc, src/update_engine/pcr_policy_post_action.h, src/update_engine/pcr_policy_post_action_unittest.cc, src/update_engine/update_attempter.cc, src/update_engine/update_attempter_unittest.cc, src/update_engine/update_metadata.proto, src/update_engine/utils.cc, src/update_engine/utils.h
Adds a new update payload data type that will contain [coreos_production_image_pcr_policy.zip](https://alpha.release.core-os.net/amd64-usr/current/coreos_production_image_pcr_policy.zip) and a new `/etc/coreos/update.conf` option `PCR_POLICY_SERVER`. When set update_engine will POST the policy zip to the given URL.
=> Add support for handling PCR policy data

coreos-setgoodroot
findmnt gets the mounted device which may be the verity dm device.
rootdev -s properly resolves the underlying partition.
Add a cgpt reapir line because I thought it already did that and it is
needed on systems where grub cannot update the backup GPT.
=> setgoodroot: fix verity systems, always perform a repair

src/update_engine/update_attempter.cc
…EED_REBOOT then update-engine.service should not update the priority flags.
=> Skip call to coreos-setgoodroot if an update has already been completed

src/update_engine/install_plan.h, src/update_engine/omaha_request_action.cc, src/update_engine/omaha_request_action.h, src/update_engine/omaha_request_action_unittest.cc, src/update_engine/omaha_response_handler_action.cc, src/update_engine/omaha_response_handler_action_unittest.cc, src/update_engine/update_attempter.cc
- submit actual update_engine version in omaha requests
- pass version through from omaha response to dbus status messages and so on
=> Report version information

src/update_engine/update_attempter.cc, src/update_engine/update_attempter.h, src/update_engine/update_attempter_unittest.cc
- Clear new version/size fields when idle
- Update last check time for "noupdate" responses
Fixes https://github.com/coreos/bugs/issues/1666
=> Small fixes for update status reporting

coreos-postinst
Azure's agent erroneously looks at the distribution name instead of its
ID. In order to rename the OS to "Container Linux", this fix is needed
to force python to always report the OS's name as "CoreOS".
This will apply to all of the OEMs where we ship python (historically,
Azure and GCE), but Azure is the only one who uses these APIs.
Eventually, the Azure agent will be updated to read the ID instead of
the name, making this unnecessary on newer instances. Unfortunately,
since we don't update the OEM partition, there will always be older
agents who require this fix.
=> coreos-postinst: patch platform.py in python libs

systemd/update-engine-stub.service, systemd/update-engine-stub.timer, systemd/update-engine.service
These `Install` sections aren't actually used, the instead the ebuild
already enables the units using multi-user.target. Nevertheless using
default.target can cause problems and so should be fixed for the sake of
documentation and consistency.
See coreos/coreos-overlay#2484 for an example of default.target breaking.
=> systemd: use multi-user.target instead of default.target

Jenkinsfile, Makefile.am, configure.ac
This also makes `configure` test `gmock` and `gtest` development files.  They don't look like they are intended to be used outside tests, but a header is always included which fails the regular build if they're not present, so always require them.
=> Add a Jenkinsfile

com.coreos.update1.service
We only listen on the system bus, and the `User` key is mandatory there.  Thus this file has never been relevant. It's too late to add `User` and `SystemdService` keys and start using proper bus activation, because we [document](https://coreos.com/os/docs/latest/update-strategies.html#disable-automatic-updates-daemon) that stopping `update-engine.service` will prevent updates from occurring until the machine is rebooted.
cc @euank
=> service: drop file

coreos-postinst
This will detect a Tectonic cluster and add the docker override flag so
that old clusters remain on docker 1.12.6. This can be removed once
Tectonic no longer supports clusters prior to 1.7.5 and Container Linux
no longer ships 1.12.6.
Still needs testing.
=> coreos-postinst: add tectonic detection logic

configure.ac, src/files/file_enumerator_posix.cc, src/strings/string_split_unittest.cc, src/update_engine/download_action_unittest.cc, src/update_engine/filesystem_iterator.cc, src/update_engine/http_fetcher_unittest.cc, src/update_engine/postinstall_runner_action_unittest.cc, src/update_engine/simple_key_value_store_unittest.cc, src/update_engine/utils.cc
This fixes warnings when building with recent glibc versions.
Part of coreos/coreos-overlay#2886
=> Fix warnings with new GCCs and glibcs

coreos-postinst
Old versions of the VMware OEM depend on `libprocps.so.3`, which is no longer going to be shipped in `/usr`. Copy `libprocps.so.3` into `/usr/share/oem/lib64` if we detect that the OEM will need it.
Tested on:
- Current QEMU image
- 490.0.0 (first version with a `vmware` VMDK)
- 505.1.0 (first version without `libguestInfo.so` `DT_RUNPATH` set to `/usr/share/oem/lib64`)
- 540.0.0 (first version with `libguestInfo.so` `DT_RUNPATH` set again)
- 921.0.0
- 1353.1.0 (last alpha with `libguestInfo.so` linked with libprocps)
- 1367.5.0 (first version with `libguestInfo.so` not linked with libprocps)
- 1786.2.0
Tests consisted of running the upgrade, rebooting, and verifying that `vmtoolsd` was running with `libguestInfo.so` mapped and, if applicable, `libprocps.so.3` mapped from …
=> coreos-postinst: copy libprocps.so.3 into OEM partition if needed
